### ISSUE TITLE
Unable to scroll parts list in PartsClient App

### ISSUE THREAD

**Issue by bmclane** [MicrosoftDocs/mslearn-dotnetmaui-consume-rest-services#10]
According to this issue, you should use a Grid instead of VerticalStackLayout
https://github.com/dotnet/maui/issues/8990

See example:
https://github.com/MicrosoftDocs/mslearn-dotnetmaui-consume-rest-services/blob/2e57f962de4f6461ccca01e3f51e8ffbb330493a/src/client/PartsClient/PartsClient/Pages/PartsPage.xaml

**Comment by codemillmatt** [comment]
Thanks for catching this one @bmclane !
