### ISSUE TITLE
Error CS0246: The type or namespace name could not be found

### ISSUE THREAD

**Issue by D3bo** [MicrosoftDocs/mslearn-dotnetmaui-consume-rest-services#3]
Debugging the PartsClient on VS for MAC 17.3 preview I'm receiving these errors:

- ViewModels/AddPartViewModel.cs  => using Android.Service.Autofill;
- ViewModels/PartsViewModel.cs => using AndroidX.Interpolator.View.Animation;
- Data/Partsmanager.cs => using using Android.Runtime;

Commenting these usings everything seems to work on both android and ios.

**Comment by Thebe01** [comment]
Same problem on VS for Windows 17.3 Preview 1.1. 
Won't work on Windows platform either if not commented.
