### ISSUE TITLE
CS0246 - Error on Build

### ISSUE THREAD

**Issue by bcookew** [MicrosoftDocs/mslearn-dotnetmaui-consume-rest-services#8]
```
Error:	CS0246	
Description: The type or namespace name 'AndroidX' could not be found (are you missing a using directive or an assembly reference?) 
Project: PartsClient (net6.0-ios), PartsClient (net6.0-maccatalyst), PartsClient (net6.0-windows10.0.19041.0)
```

Following the instructions for MS Learn in the section "Perform a GET operation to retrieve information for parts" of module "Exercise - Consume a REST service with HttpClient" I attempted to run the debugger and got this error. The debugger pointed to 
```
using AndroidX.Interpolator.View.Animation;
```
in the PartsViewModel.cs file as the issue.  hovering over the statement VS indicates the namespace is available in the project.
For clarity, I was building / debugging for Windows, not Android, at the time.

Please be kind if I have missed something obvious. 

Running VS 2022 Community v17.3 preview 2

**Comment by RonLar** [comment]
It seems that "using AndroidX.Interpolator.View.Animation;" is not necessary.  I commented it out and the build was successful for android and windows emulators.

**Comment by kgouraw** [comment]
> It seems that "using AndroidX.Interpolator.View.Animation;" is not necessary. I commented it out and the build was successful for android and windows emulators.

Yes, just remove unnecessary using dirctives

**Comment by codemillmatt** [comment]
Fixed with latest commit
